// Code generated by ent, DO NOT EDIT.

package runtime

// The schema-stitching logic is generated in issue/ent/runtime.go

const (
	Version = "v0.11.3-0.20220915080915-4425d1a6e1f3"           // Version of ent codegen.
	Sum     = "h1:two2z3AvPnk0Q1ZorgQ9dozdD8wUUyY8er0CY3OZidc=" // Sum of ent codegen.
)
